SRC = Form1.Designer.cs Form1.cs Клиент.cs Program.cs Board.cs Board.Designer.cs
FLAGS = -res:Form1.resx -res:Board.resx -r:System.Data.dll -r:System.Drawing -r:System.Windows.Forms.dll

ГрКлиент.exe: $(SRC)
	dmcs -out:ГрКлиент.exe $(FLAGS) $(SRC)
